import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from '@/context/authProvider'
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster"
import SidBar from "@/components/Comman/SidBar";
import SidBar02 from "@/components/Comman/SidBar02";
import NavBar from "@/components/Comman/NavBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
        <NavBar/>
        <div className="flex">
          <div>
            <SidBar02/>
          <SidBar/>
          </div>
          <div className="lg:ml-48">
            {children}
          </div>
        
        </div>
        
       <Toaster/>
      </body>
     
      </AuthProvider>
    </html>
  );
}
